name: Python Application

on: [push]

jobs:
  build: 
    run-on: ubuntu-latest

    steps:
    - name: check out the code
      uses: action/checkout@v2 
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
            
